spring:
  h2:
    console:
      enabled: true
  jpa:
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://localhost:3521/test
      username: sa
      password:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
    database: h2
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace